### ISSUE TITLE
fix(session): sessionManager.ts references undeclared totalPausedMs

### ISSUE THREAD

**Issue by danielcopper** [danielcopper/decky-romm-sync#634]
\`pnpm build\` emits 4 TS warnings on \`src/utils/sessionManager.ts\`:

\`\`\`
(!) [plugin typescript] src/utils/sessionManager.ts (70:3): TS2304: Cannot find name 'totalPausedMs'.
(!) [plugin typescript] src/utils/sessionManager.ts (90:3): TS2304: Cannot find name 'totalPausedMs'.
(!) [plugin typescript] src/utils/sessionManager.ts (144:5): TS2304: Cannot find name 'totalPausedMs'.
(!) [plugin typescript] src/utils/sessionManager.ts (216:3): TS2304: Cannot find name 'totalPausedMs'.
\`\`\`

Introduced in #618 (ESLint bootstrap). The eslint-unused-vars cleanup removed \`let totalPausedMs = 0;\` from line 31 because it was write-only — but the four write sites remained. At runtime in the browser these become implicit global creations (sloppy mode) or hard \`ReferenceError\` (strict mode). The rollup bundle does emit, so the warning is non-fatal at build time, but the resulting JS is broken.

## Two valid fixes

**Option A — restore the declaration** if the original intent was to subtract suspended time from final playtime. Currently \`handleGameStop()\` doesn't read \`totalPausedMs\`, so even with the declaration restored the variable would do nothing — meaning either:
  1. The read site was never wired (incomplete feature)
  2. Or the variable is genuinely dead and should be removed at the write sites too

**Option B — remove all four write sites** and accept that suspend/resume don't currently affect playtime. Cleanest if no consumer ever wired the read.

\`git log -S 'totalPausedMs' --all\` should show whether a read site ever existed.

## Suggested fix

Option B — remove the four assignments. The \`suspendedAt\` tracking still logs pause duration via \`logInfo(\`Device resumed, paused for \${...}s\`)\`, which is the observable behavior we'd lose otherwise. Playtime exclusion of suspended time was never wired into \`finalizeGameSession\`.
